### PR TITLE
Fixing path issue (to also run on MATLAB Online) and some minor typos

### PR DESCRIPTION
**Pull request by akamathmw**
@vijayiyer05 - I've made a few changes here - specifically, the helper prepare2DImageDataset file is updated to not error on line 63 when run on MATLAB Online - earlier, it used to trip up on the '/'s - possibly due to running it on a linux filesystem. 

Other minor changes include some typos fixed. Unfortunately, it appears like there are changes in the license and readme files - there are no real changes made to them content wise. 

Thanks!

### CODE REVIEW

**Review by vijayiyer05 — APPROVED** [review]
Looks good to merge.

**Comment by vijayiyer05** [comment]
Fwiw, I sort of prefer i.e. & e.g. without the trailing commas which seem like far too much punctuation. But I've learned the grammar gods overruled me on this one ¯\_(ツ)_/¯

**Comment by akamathmw** [comment]
Thanks for reviewing this, @vijayiyer05 - I don't seem to have write permissions to merge this - would you mind please doing so?

**Comment by akamathmw** [comment]
@vijayiyer05 - thanks for providing maintainer access - I'll merge and then check to make sure nothing is broken (I checked earlier in my repository, but just in case). Thanks!

**Comment by akamathmw** [comment]
This is tested on both desktop and online. To load this on MATLAB online, use:
>> websave("brainMRIexample", "https://github.com/matlab-deep-learning/Brain-MRI-Age-Classification-using-Deep-Learning/archive/refs/heads/master.zip")

Thanks for all the help!

**Pull request merged**
